### ISSUE TITLE
Can't find column in composite key

### ISSUE THREAD

**Issue by lucasgmagalhaes** [zzzprojects/Dapper-Plus#104]
![image](https://user-images.githubusercontent.com/19666463/148556024-5b697971-2bc2-4b08-8ea3-2c5d3aa20ae4.png)

When I try to map an entity with composite keys that references to columns in database with snake case naming this error is thrown:

```cmd
An error occured while resolving mapping by name. See the inner exception for details
    ---- System.Exception : Missing Column : UnbId
    On entity : ProgramExecution
    On Table : "program_executions"
```

I'm trying to do a bulkMerge:

```csharp
context.BulkMerge(toUpsert);
```

**Comment by JonathanMagnan** [comment]
Hello @lucasgmagalhaes ,

The issue is that the `Map` only map the property to the column you specified.

However, the key method doesn't use the column name you specified in the `Map` property. So you need to map it again to the right column name

```csharp
mapper.Key(x => x.UnbId, "unb_id")
	  .Key(x => x.GeoId, "geo_id")
	  .Key(x => x.ProgramCode, "programe_code")
	  .Key(x => x.ReferenceDate, "reference_date")
	  .Key(x => x.Start, "start")
	  .Key(x => x.End, "end")
```

We will check on our side how we could force the key to use either name you specified in the `Map` method (such adding a boolean since we need to say backward compatible) or adding a new method that will be specified for this.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @lucasgmagalhaes ,

Did you try our alternative solution using multiple key methods?

After some discussion, I do not think we will do anything with the `Map` method.
