### ISSUE TITLE
Upgrade to .NET Core

### ISSUE THREAD

**Issue by lucasgmagalhaes** [zzzprojects/Dapper-Plus#105]
Are there any plans to upgrade the library to .NET Core? I know it's compatible, but .NET Core has a much better performance comparable to .NET Framework. And I also noticed that it's running in framework 4.5, not even the latest version of it (4.8). If upgrade the library to just .net 3.1 would be a great approach and be very helpful.

**Comment by JonathanMagnan** [comment]
Hello @lucasgmagalhaes ,

Sorry, we missed this issue.

Our library already supports .NET Core since a few years ago.

We currently support:
 - .NET Standard 2.0 (so .NET Core 2 or better)
 - .Net6.0 (So .NET 6 or better)

See: https://www.nuget.org/packages/Z.Dapper.Plus/#dependencies-body-tab

Best Regards,

Jon
