### ISSUE TITLE
How to sync part of the table

### ISSUE THREAD

**Issue by ipavlovi** [zzzprojects/Dapper-Plus#113]
We have already purchased license for Entity Framework Extensions. Now we are evaluating your other library, z.dapperplus bulk operations library and we have some questions regarding that library.

We have a list which we want to synchronize with the part of the table which satisfy condition, and do not want to change the other part of the table which does not satisfy the same condition.

How to recognize which rows are inserted/updated/deleted after each bulk operation.

**Comment by JonathanMagnan** [comment]
Hello @ipavlovi ,

To synchronize only a part of the table, you need the option: `ColumnSynchronizeDeleteKeySubsetExpression`

```csharp
DapperPlusManager.Entity<Order>("Order_Synchronize").Table("Orders").Key(x => new { x.Number}).UseBulkOptions(x => x.ColumnSynchronizeDeleteKeySubsetExpression = c => new { c.CustomerID });
```

Fiddle: https://dotnetfiddle.net/fbFJLW

To know which value has been inserted/updated/deleted after each bulk operation, you can get this information using the `Audit` feature: https://dapper-plus.net/audit

Let me know if you need more help with your scenario.

Best Regards,

Jon

**Comment by DTIBeograd** [comment]
Hello Jon,

Seems that we have managed to get what is required, by using ColumnSynchronizeDeleteKeySubsetExpression.

However, how can we ignore null value error on insert in case we have default value set in DB?
Is this the right way? options.IgnoreOnSynchronizeInsertExpression = x=> x.DateTimeColumn;

Thanks

**Comment by DTIBeograd** [comment]
Also, is there a way to cast AuditEntries to the original object?

**Comment by DTIBeograd** [comment]
Dear Jon,

We have managed to find solution for problem above, there is only one left.
When calling AlsoBulkSynchronize to sync child object, AlsoBulkSynchronize is not aware that parent is not synchronized(skipped since its already in database) and it is trying to sync child regardless. The reason we are getting an error is that in child object is not getting and id of parent in that case.
Can we somehow skip child object synchronizing if there is no action happening on parent? Or can we pass parent ID from database to the child if there is no action on parent object?

Thanks

**Comment by JonathanMagnan** [comment]
Hello @DTIBeograd ,

Could you try with the option `options.ForceOutputFromUnmodifiedRow= true;`

Since you skip the `Update` part, the `IdentityKey` is not returning. The value should now be returned by forcing to output also `UnmodifiedRow`. You might need to specify you want to output the `IdentityKey` but I do not believe that's needed.

Let me know if that is working.

Best Regards,

Jon

**Comment by DTIBeograd** [comment]
It does work, but as I have noticed it acts as Update action according to AuditEntry.
Is there a way to do just BulkDelete with similar option as "IgnoreOnSynchronizeInsertExpression"

Thanks,
Alek

**Comment by JonathanMagnan** [comment]
Hello @DTIBeograd ,

## It does work, but as I have noticed it acts as Update action according to AuditEntry.

If you look at the SQL generated, it indeed performs an `Update` but on a variable and doesn't change any column values. That's the easiest solution for us as we need to know which identity should go to which `ZZZ_Index` (the position of your entity in the list you provided).

Let me know if that's clear or you need a better explanation.

## Is there a way to do just BulkDelete with similar option as "IgnoreOnSynchronizeInsertExpression"

I do not understand the question or what you want to try to do here. Let me know more about it

**Comment by DTIBeograd** [comment]
I want to delete part of the table based on sub key and not to delete objects provided in the list, I have made a mistake in the last question instead of "IgnoreOnSynchronizeInsertExpression" I wanted to ask  "Is there a way to do just BulkDelete with similar option as ColumnSynchronizeDeleteKeySubsetExpression" so basically BulkDelete to act as BulkSynchronize delete part.

Thanks

**Comment by JonathanMagnan** [comment]
Hello @DTIBeograd ,

Thank you for the additional information, the question makes way more sense ;)

I will look at it with my developer.

**Comment by JonathanMagnan** [comment]
Hello @DTIBeograd ,

My developer just told me that we have the option `SynchronizeOnlyDelete = true`

So only the `Delete` part from the synchronize will be done (Insert and Update will be skipped)

Is this option could work for you?

**Comment by DTIBeograd** [comment]
Yeah that would be fine too.

Thanks

**Comment by DTIBeograd** [comment]
Hello Jon,

Now I'm having problem mapping enum property to to ms sql column

.Map(x=>x.property, "propertyId")

property is an enum type

Getting an error:
Exception: Missing Column : property
On entity : EntityName
On Table : [TableName]

Have no problems with other property mapping.

Thanks

**Comment by JonathanMagnan** [comment]
Hello @DTIBeograd ,

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue.

**Comment by DTIBeograd** [comment]
At some point ill try to make test app.

Got another question since I cannot find a lot of documentation regarding AllowDuplicateKeys option.
If I have an list of objects
position 1 object key 1
position 2 object key 2
position 3 object key 3
position 4 object key 1
and if AllowDuplicateKeys option is enabled,
will last object at position 4 overwrite object at position 1?

Thanks

**Comment by DTIBeograd** [comment]
For BulkMerge i had to set AllowDuplicateKeys = true, so it was not default behavior, however, explanation is completely clear, thanks.

**Comment by JonathanMagnan** [comment]
Hello @DTIBeograd ,

You are right. I just double-checked the code and we have to remove this option by default a few months ago (was causing some issues with provider outside of SQL Server)

So you indeed need to enable it.
