### ISSUE TITLE
plan to release real Async  method

### ISSUE THREAD

**Issue by znyet** [zzzprojects/Dapper-Plus#119]
hello JonathanMagnan.
When do you plan to release the real Async method.

**Comment by JonathanMagnan** [comment]
Hello @znyet ,

Unfortunately, we could not agree on how to add `async` method to bulk operations due to how chaining action currently work in Dapper Plus.

Currently, using `Async` can only be done with the `BulkActionAsync`.

Here is an example with a cancellation token:

```csharp
var task = connection.BulkActionAsync(x => x.BulkInsert(invoices).ThenBulkInsert(y => y.InvoiceItems), cancellationToken);
```

Doc: https://dapper-plus.net/async-action

Best Regards,

Jon
