### ISSUE TITLE
ILogger not logging, but Console.WriteLine works?

### ISSUE THREAD

**Issue by VictorioBerra** [zzzprojects/Dapper-Plus#126]
```csharp

            this.logger.LogInformation("Starting bulk stuff..."); // WORKS

            await transaction
                .UseBulkOptions(options =>
                {
                    options.BatchSize = this.workDayStoreLocationsServiceOptions.DapperPlusBulkOperationBatchSize;
                    options.BatchTimeout = this.workDayStoreLocationsServiceOptions.DapperPlusBulkOperationBatchTimeout;
                    options.RetryCount = this.workDayStoreLocationsServiceOptions.DapperPlusBulkOperationRetryCount;

                    // options.Log = s => this.logger.LogInformation("Working..."); // DOES NOT WORK
                    options.Log = s => Console.WriteLine("Working..."); // WORKS!
                })
                .BulkActionAsync(
                    x => x.BulkSynchronize(
                            LocationsMappings.DatabaseLocationMappingKey,
                            locationEntities)
                        .Include(x =>
                            x.ThenBulkSynchronize(
                                LocationsMappings.DatabaseLocationTypeMappingKey,
                                location => location.LocationTypes))
                    cancellationToken);
```

I am using Serilog and I get logging output everywhere but `BulkOptions ... options.Log` does not ever seem to work with ILogger.

Any ideas?

**Comment by JonathanMagnan** [comment]
Hello @VictorioBerra ,

Could you try the code again without being `async`? So without the `BulkActionAsync`.

We are currently unsure why this issue happens, but we are pretty sure it caused because the code is being executed asynchronously.

I found this question on [Stack Overflow](https://stackoverflow.com/questions/70929402/ilogger-instance-does-not-log-in-async-method-but-console-writeline-does), perhaps you will find an explanation from it. Some parts look pretty much like yours.

Let me know if you need more help with this issue.

Best Regards,

Jon

**Comment by VictorioBerra** [comment]
Turns out I had a filter excluding specific messages, sorry about that. Looks like its working as intended! Thanks for checking StackOverflow that helped point me in the right direction.

**Comment by JonathanMagnan** [comment]
Awesome @VictorioBerra ,

Thank you for letting us know.

Have a great day,

Best Regards,

Jon
