### ISSUE TITLE
BulkMerge not executing trigger

### ISSUE THREAD

**Issue by seanfisher** [zzzprojects/Dapper-Plus#15]
BulkMerge will execute a trigger on the first column but not the second in a two-row batch.

Trigger like this:

```
CREATE TRIGGER [dbo].[Trigger_MyTable_CreatedOn]
    ON [dbo].[MyTable]
    FOR INSERT, UPDATE
    AS
		DECLARE @id int;
		DECLARE @currenttime datetime;

		SELECT @id=i.Id FROM inserted i;
		SET @currenttime=SYSUTCDATETIME();
    BEGIN
		UPDATE [dbo].[MyTable] SET LastModified=@currenttime WHERE Id=@id;
    END
GO
```

Merge c# code:

```
DapperPlusManager.Entity<MyTable>().Table("MyTable").Key(myEntity =>
    new {myEntity.Column1, myEntity.Column2, myEntity.Column3});
connection.BulkMerge(myEntities);
```

I'll bulk merge two entities and the result will look like this:

| Id | Column1 | Column 2 | Column 3  | LastModified             |
|----|-----------|------------|------------|-------------------------|
| 1  | ... | ... | ... |  2017-11-13 21:54:12.790 |
| 2  | ... | ... | ... | NULL                     |

Any ideas?

**Comment by JonathanMagnan** [comment]
Hello @seanfisher ,

This issue is not caused by our library but by the way you use `TRIGGER`

You assume the table `inserted` contains only one row. But `inserted` is a table, it can contains multiple rows and in this case, your trigger doesn't work. It will only perform the logic on the last `id` set to the variable `@id`

I believe your code should look like this:

```csharp
CREATE TRIGGER [dbo].[Trigger_MyTable_CreatedOn]
    ON [dbo].[MyTable]
    FOR INSERT, UPDATE
    AS
		DECLARE @currenttime datetime;
		SET @currenttime=SYSUTCDATETIME();
		
    BEGIN
		UPDATE A
			SET LastModified=@currenttime
		FROM [dbo].[MyTable] AS A
		INNER JOIN inserted AS B ON A.Id = B.Id
    END
GO
```

Let me know if that helped you and if you understand correctly the mistake in the way your trigger is coded.

Best Regards,

Jonathan

**Comment by seanfisher** [comment]
Awesome Jonathan, that was indeed the issue. Thank you!!
