### ISSUE TITLE
Is Audit the only way of getting inserted Id's?

### ISSUE THREAD

**Issue by cdbridger-tracplus** [zzzprojects/Dapper-Plus#150]
when using 

```
await this.database.BulkInsert(newItems);
```

is there any other way of getting the items with the updated ids? Or having `newItems` have the database generated Keys set on it without having to create a new list and passing it to bulk options audit entries?

**Comment by JonathanMagnan** [comment]
Hello @cdbridger-tracplus ,

It depends on what exactly you want. People usually use one of the two following mapping:
- `.Identity(x => x.MyID)`
- `Output(x => x.MyID)`

In both cases, your entities will be populated by the identity generated on the database side. You can retrieve the identity value by just looking at your entities instead of using the audit feature.

You can learn more from [Fluent Mapping](https://dapper-plus.net/mapping#fluent-api-mapping) and [Identity Propagation](https://dapper-plus.net/identity-key-propagation#auto-identity-propagation) in those articles

Let me know if that answers your question.

Best Regards,

Jon

**Comment by cdbridger-tracplus** [comment]
I can't seem to get it to work

![image](https://github.com/user-attachments/assets/2fa7f338-7303-48f4-b237-e359317450c2)

As you can see in the above image, the entities passed in don't have their Id's set after calling BulkInsert (they are still null, although the database has generated the id values for them in the database)

Here is the model:

![image](https://github.com/user-attachments/assets/e1642b8d-dcbc-4a1a-a6f9-d4563ce11621)

Here is my DapperPLusManager Setup

![image](https://github.com/user-attachments/assets/c3ceaf37-2d71-46eb-ab38-a438949bf52c)

I'm assuming I'm doing something fundamentally wrong if the entities are supposed to have their Database Id's populated on them (in memory) after I insert them but I can't tell what from reading the docs.

(This is why after I insert I'm currently doing a get all  after insert which is obviously bonkers)

**Comment by JonathanMagnan** [comment]
Hello @cdbridger-tracplus ,

First, you don't need to specify the `Output` mapping (you probably did it because you tried everything hehe)

I have a big hypothesis about why you don't see the IDs. You are currently passing an `IEnumerable` of markers and not a list or an array. So what probably happens is every time you iterate over this `IEnumerable`, you recreate the list from scratch. For example, if the list comes by reading a file, you read that file every time a method like `ToList` is called to this `IEnumerable`.

If you transform this `IEnumerable` to a list first, you will see the `Ids` populated correctly.

Let me know if that cause and solution were clear enough.

Best Regards,

Jon

**Comment by cdbridger-tracplus** [comment]
Ah that was the trick! Thank you very much.
