### ISSUE TITLE
MERGE sql instruction on BulkInsert

### ISSUE THREAD

**Issue by LbISS** [zzzprojects/Dapper-Plus#2]
Hi.

I'm trying to use BulkInsert in Dapper-Plus v.1.0.7
`Z.Dapper.Plus.DapperPlusExtensions.BulkInsert(cnn, entities);`

and in result gettings SQL script like

```
MERGE INTO [ExtParamHistory] AS DestinationTable
USING
(
SELECT @0_0 AS [ExtParamValue], @0_1 AS [DT], @0_2 AS [UserID], @0_3 AS [TaskID], @0_4 AS [ExtParamID], @0_5 AS [Comment], @0_6 AS [NativeValue], @0_7 AS [ID], @0_8 AS ZZZ_Index
) AS StagingTable
ON 1 = 2
WHEN NOT MATCHED THEN
   INSERT ( [ExtParamValue], [DT], [UserID], [TaskID], [ExtParamID], [Comment], [NativeValue] )
   VALUES ( [ExtParamValue], [DT], [UserID], [TaskID], [ExtParamID], [Comment], [NativeValue] )
OUTPUT
   $action,
   StagingTable.ZZZ_Index,
   INSERTED.[ID] AS [ID_zzzinserted]
```

It's making empty useless join/scan on big table. Why it's not using simple insert?

**Comment by zzzprojects** [comment]
Hello @LbISS ,

We are currently re-writing the library to avoid "MERGE" whenever is possible (To make simple INSERT, UPDATE, DELETE statement instead).

In this case, the MERGE allow us to know which index for the entities list (ZZZ_Index) is related to which identity values inserted (ID_zzzinserted) to output the value and set correctly the identity value to the right entity.

This is impossible to do without a MERGE statement, the INSERT OUTPUT doesn't provide the flexibility and robustness to know exactly the index.

Since the match is done with the predicate "1 = 2", the statement doesn't try to scan the table. By example, we did a test on a table with 100,000 rows, only 3 logical reads has been performed (the same number as 1 row)

Let me know if this answer correctly to your question.

Best Regards,

Jonathan

**Comment by denisdrake** [comment]
Is it included in .12 release?

**Comment by JonathanMagnan** [comment]
Hello @denisdrake ,

There is no issue in this thread. Only an amelioration which will be plan for the next major version. So I'm not sure for which fix you are looking for.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing comment: We answered to @LbISS  and no comment from @denisdrake
