### ISSUE TITLE
BulkMerge inside transaction

### ISSUE THREAD

**Issue by micky53** [zzzprojects/Dapper-Plus#3]
Hello.

In my case I need using BulkMegre method inside our transaction. Example source code:

```
using (var cnn = new SqlConnection("..."))
{
	cnn.Open();
	using (var tran = cnn.BeginTransaction())
	{
		cnn.BulkMerge(entities);
	}
}
```

But BulkMerge throw exception: [ex.txt](https://github.com/zzzprojects/Dapper-Plus/files/704234/ex.txt)
Can you help?

**Comment by JonathanMagnan** [comment]
Thank you,

The issue happens because of the transaction. We will fix this issue today or over the weekend.

Meanwhile, you can use ScopeTransaction

See: https://msdn.microsoft.com/en-us/library/system.transactions.transactionscope(v=vs.110).aspx

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @micky53 ,

The v1.0.12 has been released.

We added extension methods to IDbTransaction.

You can now use the following code:
```csharp
using (var cnn = new SqlConnection("..."))
{
	cnn.Open();
	using (var tran = cnn.BeginTransaction())
	{
		tran.BulkMerge(entities);
	}
}
```

It seemed more logic to add an extension method to the transaction instead of adding multiple overloads or a method specific to set the transaction. Let me know if this solution satisfies your requirement or you would like to have a better solution.

Best Regards,

Jonathan
