### ISSUE TITLE
BulkMerge insert/update rows affected

### ISSUE THREAD

**Issue by Gavriloski** [zzzprojects/Dapper-Plus#34]
Hello.
I am trying to get info about how many rows were updated and how many inserted. 
Is this even possible with BulkMerge operation ?

Possibly to see how many of them failed to update or insert if it's not exception.

Thanks.

**Comment by JonathanMagnan** [comment]
Hello @Gavriloski ,

Unfortunately, that option is not yet available. Since we support multiple ways to insert/merge and when some options were enabled, it was impossible to get the real count, we choose to not getting this important information when we created the library (which we now understand was a bad decision).

When we will re-write the library, we will not make this mistake again but meanwhile, there are no options to get the row affected.

Best Regards,

Jonathan

**Comment by Gavriloski** [comment]
@JonathanMagnan 
Thanks for fast replay.
Is there any way to get this infromation when using BulkMerge in conjunction with DbTransaction ? 
I tried using Transaction property which was on DapperPlusActionSet but it didn't have anything relevant.

Is there maybe any other way I can get this transaction when using BulkMerge?

Thanks.

**Comment by JonathanMagnan** [comment]
Hello @Gavriloski ,

I'm not sure to understand the question.

Which information do you want to get with `BulkMerge` and `DbTransaction`?

When using a transaction, you normally use extension method on the DbTransaction instead: http://dapper-plus.net/transaction

Best Regards,

Jonathan

**Comment by Gavriloski** [comment]
I thought using Transaction would be enough to provide data I need (numbers of rows inserted and number of rows updated).
Is it possible to get atlest rows affected. 
As shown here : http://dapper-tutorial.net/transaction
But this is not dapper plus not sure how they extend on each other. 

Actually I tried recreating this code but I couldn't find way to get rows affected. 
Is it doable to get rows affected with BulkMerge operation ?

**Comment by JonathanMagnan** [comment]
Hello @Gavriloski ,

No, it's not possible to get rows affected in our library.

**Comment by Gavriloski** [comment]
@JonathanMagnan 
Thank you for your time.
You can close this now.

Thanks.
